### ISSUE TITLE
Update mesh when destroying block

### ISSUE THREAD

**Issue by Nolat** [Rausy/osuve#20]
Hi, I'm updating chunk meshes, when I'm destroying a block. But block in border chunk won't update, but border chunk are calling the GenerateMesh function.

Do you have any idea why is this not working ?

**Comment by FireImp834** [comment]
No but I might be able to help you with it.
                                 thanks for letting me know.
 Write me a letter back please

**Comment by Nolat** [comment]
@FireImp834 It would be nice 😄

**Comment by Rausy** [comment]
Updating chunks through modification (adding/destroying blocks) has not been rigorously tested yet, and mesh generation in between borders is a known issue.

More accurately it's a temporarily removed feature (?) as I'm trying to make it compatible with grass blocks that can check for blocks in a diagonal chunk to generate side grass textures.

**Comment by Nolat** [comment]
Hi, how could I been able to enable this feature ?

**Comment by Rausy** [comment]
I don't recall if this was something I pushed yet or not, so take it with a grain of salt. If I did, it's either commented out and incompatible with the current code changes or outright deleted, again, don't take my word for it.

I'll check this issue out later when I get back home.

**Comment by Nolat** [comment]
Ok Thanks !

**Comment by Nolat** [comment]
I didn't find anything in your code, can you tell me if you find a way to fix this issue.
Thanks
